GET http://localhost:3000/users

###

GET http://localhost:3000/subscribers/6410913ab07c54a24b028807

### 

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Jim Williams",
    "subscribedToChannel": "Web Dev Simplified"
}

### 
POST https://epistemica-x-db.vercel.app/api/user/login
Content-Type: application/json

{
    "email":"g.ferowich@gmail.com",
    "password":"legend"
}
###
POST https://epistemica-x-db.vercel.app/api/basket/post
Content-Type: application/json

{
    "basketNameStr": "2023 Bitcoin",
    "user_IDStr": "646678e5024aad67cf201bfb",
    "indexDateStr": "01-01-2023",
    "initialBasketValueInt": "1000",
    "asset1HM": {
        "asset1NameStr": "Bitcoin",
        "asset1IndexPriceInt": "10000", 
        "asset1QuantityInt": "0.1", 
        "asset1WeightInt": "100",
        "asset1APIKeyStr": "bitcoin"
    },
    "asset2HM": {
        "asset2NameStr": "",
        "asset2IndexPriceInt": "", 
        "asset2QuantityInt": "",
        "asset2WeightInt": "",
        "asset2APIKeyStr": ""
    },
    "asset3HM": {
        "asset3NameStr": "",
        "asset3IndexPriceInt": "",
        "asset3QuantityInt": "",
        "asset3WeightInt": "",
        "asset3APIKeyStr": ""
    },
    "asset4HM": {
        "asset4NameStr": "",
        "asset4IndexPriceInt": "",
        "asset4QuantityInt": "",
        "asset4WeightInt": "",
        "asset4APIKeyStr": ""
    },
    "asset5HM": {
        "asset5NameStr": "",
        "asset5IndexPriceInt": "", 
        "asset5QuantityInt": "",
        "asset5WeightInt": "",
        "asset5APIKeyStr": ""
    }
  }