GET http://localhost:3000/users

###

GET http://localhost:3000/subscribers/6410913ab07c54a24b028807

### 

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Jim Williams",
    "subscribedToChannel": "Web Dev Simplified"
}

### 
POST https://epistemica-x-db.vercel.app/api/user/login
Content-Type: application/json

{
    "email":"g.ferowich@gmail.com",
    "password":"legend"
}

###
POST https://epistemica-x-db-git-main-clariti23.vercel.app/api/basket/post
Content-Type: application/json

{
    "basketNameStr": "2023 Bitcoin",
    "user_IDStr": "646678e5024aad67cf201bfb",
    "indexDateStr": "01-01-2023",
    "initialBasketValueInt": 1000,
    "presentBasketValueInt": 2000,
    "percentReturnInt": 100,
    "asset1HM": {
        "asset1NameStr": "Bitcoin",
        "asset1IndexPriceInt": 10000, 
        "asset1QuantityInt": 0.1, 
        "asset1WeightInt": 100,
        "asset1APIKeyStr": "bitcoin",
        "asset1LoSStr": "long"
    },
    "asset2HM": {
        "asset2NameStr": "",
        "asset2IndexPriceInt": 0, 
        "asset2QuantityInt": 0,
        "asset2WeightInt": 0,
        "asset2APIKeyStr": "",
        "asset2LoSStr": "long"
    },
    "asset3HM": {
        "asset3NameStr": "",
        "asset3IndexPriceInt": 0,
        "asset3QuantityInt": 0,
        "asset3WeightInt": 0,
        "asset3APIKeyStr": "",
        "asset3LoSStr": "long"
    },
    "asset4HM": {
        "asset4NameStr": "",
        "asset4IndexPriceInt": 0,
        "asset4QuantityInt": 0,
        "asset4WeightInt": 0,
        "asset4APIKeyStr": "",
        "asset4LoSStr": "long"
    },
    "asset5HM": {
        "asset5NameStr": "",
        "asset5IndexPriceInt": 0, 
        "asset5QuantityInt": 0,
        "asset5WeightInt": 0,
        "asset5APIKeyStr": "",
        "asset5LoSStr": "long"
    }
}

// the coins post request works as of Saturday
// June 3, 2023 || 2:43pm.
### 
POST https://epistemica-x-db-git-main-clariti23.vercel.app/api/coin/post
Content-Type: application/json

{
"ath": 1.17,
"ath_change_percentage": -14.7576,
"ath_date": "2019-05-08T00:40:28.300Z",
"atl": 0.877647,
"atl_change_percentage": 13.90038,
"atl_date": "2023-03-11T08:02:13.981Z",
"circulating_supply": 28907428651.463,
"current_price": 0.999554,
"fully_diluted_valuation": 28892995696,
"high_24h": 1.002,
"id": "usd-coin",
"image": "https://assets.coingecko.com/coins/images/6319/large/USD_Coin_icon.png?1547042389",
"last_updated": "2023-06-03T18:52:17.592Z",
"low_24h": 0.997862,
"market_cap": 28892995696,
"market_cap_change_24h": -44049832.3671608,
"market_cap_change_percentage_24h": -0.15223,
"market_cap_rank": 5,
"max_supply": null,
"name": "USD Coin",
"price_change_24h": -0.000878059010024468,
"price_change_percentage_24h": -0.08777,
"roi": null,
"symbol": "usdc",
"total_supply": 28907428651.463,
"total_volume": 1406126561
}

###
GET https://epistemica-x-db-git-main-clariti23.vercel.app/api/time/get
Content-Type: application/json